name: CI / Quality checks (22.x)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Workspace sanity
        run: |
          node -p "process.versions"
          pwd && ls -la
          test -f package.json && test -f package-lock.json
      - name: Install
        run: npm ci --no-audit --no-fund
      - run: npm run typecheck
      - run: npm run lint
      - name: Unit tests (no network)
        run: npm run coverage --if-present
      - name: OpenNext CLI available
        run: node -e "require.resolve('@opennextjs/cloudflare/package.json')" || true
      - name: Build (no deploy)
        run: npm run build --if-present
