name: "Dependabot Auto-Merge"

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - reopened
      - synchronize

jobs:
  auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const allowed = pr.user.login === 'dependabot[bot]';
            if (!allowed) {
              core.info('Auto-merge skipped: not a Dependabot PR.');
              return;
            }
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'squash'
            });
