name: "SBOM"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate CycloneDX SBOM
        run: npm run sbom:cyclonedx --if-present

      - name: Generate SPDX SBOM
        run: npm run sbom:spdx --if-present

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifacts
          path: |
            sbom-cyclonedx.json
            sbom-spdx.json
          if-no-files-found: error
